import 'package:flutter/material.dart';
import 'update_service.dart';

class LocalizationService {
  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_name': '', // Empty means use update.json app_name
      'home': 'Home',
      'gold': 'Gold',
      'currency': 'Currency',
      'calculate': 'Calculator',
      'contact': 'Contact',
      'settings': 'Settings',
      'theme': 'Theme',
      'language': 'Language',
      'search_gold': 'Search gold type...',
      'search_currency': 'Search currency...',
      'last_update': 'Last Update',
      'offline_data': 'Showing offline data',
      'live': 'Live',
      'offline': 'Offline',
      'no_connection': 'No Connection',
      'market_summary': 'Market Summary',
      'my_favorites': 'My Favorites (Top 5)',
      'services': 'Our Services',
      'contact_channels': 'Communication Channels',
      'telegram_subtitle': 'Live signals and announcements',
      'whatsapp_subtitle': 'Fast support line',
      'copy_clipboard': 'Copied to clipboard!',
      'converter': 'Converter',
      'converter_subtitle': 'Enter amount and select asset.',
      'amount': 'Amount',
      'try_amount': 'TRY Amount',
      'estimated_total': 'Estimated Total (TL)',
      'purchasable_amount': 'Purchasable Amount',
      'quick_calcs': 'Quick Calculations',
      'gram_gold_10': '10 Grams Gold',
      'dollar_100': '100 Dollars',
      'quarter_gold_5': '5 Quarter Gold',
      'version': 'Version',
      'appearance': 'Appearance',
      'app_settings': 'App Settings',
      'auto_refresh': 'Auto Refresh',
      'about': 'About',
      'system_default': 'System Default',
      'light': 'Light',
      'dark': 'Dark',
      'update_available': 'New Version Available',
      'current_version': 'Current Version',
      'new_version': 'New Version',
      'whats_new': 'What\'s New',
      'later': 'Later',
      'update': 'Update',
      'choose_language': 'Choose Language',
      'choose_language_settings_hint': 'You can change this anytime in Settings.',
      'continue': 'Continue',
      'corporate': 'Contact',
      'reliable_market': 'Reliable & Live Markets',
      'gold_bar': 'Gold Bar',
      'gold_swap': 'Gold Swap',
      'gold_analysis': 'Gold Analysis',
      'global_rate': 'Global Rate',
      'whatsapp': 'WhatsApp',
      'phone_label': 'Phone',
      'address': 'Address',
      'telegram_group': 'Telegram Group',
      'choose_theme': 'Choose Theme',
      'update_interval': 'Update Interval',
      'minutes': 'Minutes',
      'off': 'Off',
      'login': 'Login',
      'register': 'Register',
      'profile': 'Profile',
      'email': 'Email',
      'password': 'Password',
      'full_name': 'Full Name',
      'phone_field': 'Phone Number',
      'profession': 'Profession',
      'required': 'Required',
      'min_characters': 'Min 6 characters',
      'loyalty_points': 'Your Loyalty Points:',
      'total_points': 'Total Points',
      'logout': 'Sign Out',
      'login_benefit': 'Sign in to enjoy exclusive member benefits.',
      'error': 'Error',
      'registration_success': 'Registration successful! Please check your email.',
      'invalid_email_format': 'Please enter a valid email address.',
      'rate_limit_error': 'Too many attempts. Please wait a few minutes.',
      'profile_creation_error': 'Account created, but profile setup failed. Please contact support.',
      'unknown_error': 'An unexpected error occurred. Please try again.',
      'logout_confirm_title': 'Sign Out',
      'logout_confirm_msg': 'Are you sure you want to sign out?',
      'yes': 'Yes',
      'no': 'No',
      'account_info': 'Account Information',
      'public_profile': 'Public Profile',
      'signup_reminder': 'Sign up for exclusive member benefits and loyalty points!',
      'prof_jeweler': 'Jeweler',
      'prof_gold_dealer': 'Gold Dealer',
      'prof_currency': 'Currency Exchange',
      'prof_investor': 'Investor',
      'prof_other': 'Other',
      'select_image': 'Select Profile Picture',
      'uploading': 'Uploading...',
      'upload_success': 'Profile picture updated!',
      'upload_error': 'Upload failed. Please try again.',
      'cancel': 'Cancel',
      'edit': 'Edit',
      'code_GA': 'Gram Gold',
      'code_C': 'Quarter Gold',
      'code_Y': 'Half Gold',
      'code_T': 'Full Gold',
      'code_CMR': 'Republic Gold',
      'code_ATA': 'Ata Gold',
      'code_GAG': 'Gram Silver',
      'code_XAUUSD': 'Ounce Gold',
      'code_XHGLD': 'Has Gold',
      'code_14': '14 Karat Gold',
      'code_18': '18 Karat Gold',
      'code_22': '22 Karat Bracelet',
      'code_IKB': 'Two and a Half Gold',
      'code_BSL': 'Fivefold Gold',
      'code_GR': 'Gremse Gold',
      'code_RA': 'Resat Gold',
      'code_HA': 'Hamit Gold',
      'code_XAUXAG': 'Gold/Silver Ratio',
      'code_USD': 'Dollar',
      'code_EUR': 'Euro',
      'code_AED': 'Dirhem',
      'code_USDT': 'Tether (USDT)',
    },
    'tr': {
      'app_name': '',
      'home': 'Ana Sayfa',
      'gold': 'Altın',
      'currency': 'Döviz',
      'calculate': 'Hesapla',
      'contact': 'İletişim',
      'settings': 'Ayarlar',
      'theme': 'Tema',
      'language': 'Dil',
      'search_gold': 'Altın türü ara...',
      'search_currency': 'Döviz ara...',
      'last_update': 'Son Güncelleme',
      'offline_data': 'Çevrimdışı veriler gösteriliyor',
      'live': 'Canlı',
      'offline': 'Çevrimdışı',
      'no_connection': 'Bağlantı Yok',
      'market_summary': 'Piyasa Özeti',
      'my_favorites': 'Favorilerim (Üst 5)',
      'services': 'Hizmetlerimiz',
      'contact_channels': 'İletişim Kanalları',
      'telegram_subtitle': 'Canlı sinyaller ve duyurular',
      'whatsapp_subtitle': 'Hızlı destek hattı',
      'copy_clipboard': 'Panoya kopyalandı!',
      'converter': 'Dönüştürücü',
      'converter_subtitle': 'Miktarı girin ve varlığı seçin.',
      'amount': 'Miktar',
      'try_amount': 'TL Tutarı',
      'estimated_total': 'Tahmini Tutar (TL)',
      'purchasable_amount': 'Alınabilecek Miktar',
      'quick_calcs': 'Hızlı Hesaplamalar',
      'gram_gold_10': '10 Gram Altın',
      'dollar_100': '100 Dolar',
      'quarter_gold_5': '5 Çeyrek Altın',
      'version': 'Versiyon',
      'appearance': 'Görünüm',
      'app_settings': 'Uygulama Ayarları',
      'auto_refresh': 'Otomatik Güncelleme',
      'about': 'Hakkında',
      'system_default': 'Sistem Varsayılanı',
      'light': 'Aydınlık',
      'dark': 'Karanlık',
      'update_available': 'Yeni Versiyon Mevcut',
      'current_version': 'Mevcut Versiyon',
      'new_version': 'Yeni Versiyon',
      'whats_new': 'Yenilikler',
      'later': 'Daha Sonra',
      'update': 'Güncelle',
      'choose_language': 'Dili Seçin',
      'choose_language_settings_hint': 'Bunu istediğiniz zaman Ayarlar\'dan değiştirebilirsiniz.',
      'continue': 'Devam Et',
      'corporate': 'İletişim',
      'reliable_market': 'Güvenilir ve Canlı Piyasalar',
      'gold_bar': 'Külçe Altın',
      'gold_swap': 'Döviz Takas',
      'gold_analysis': 'Altın Analiz',
      'global_rate': 'Global Kur',
      'whatsapp': 'WhatsApp',
      'phone_label': 'Telefon',
      'address': 'Adres',
      'telegram_group': 'Telegram Grubu',
      'choose_theme': 'Tema Seçin',
      'update_interval': 'Güncelleme Aralığı',
      'minutes': 'Dakika',
      'off': 'Kapalı',
      'login': 'Giriş Yap',
      'register': 'Kayıt Ol',
      'profile': 'Profil',
      'email': 'E-posta',
      'password': 'Şifre',
      'full_name': 'Ad Soyad',
      'phone_field': 'Telefon Numarası',
      'profession': 'Meslek',
      'required': 'Gerekli',
      'min_characters': 'En az 6 karakter',
      'loyalty_points': 'Sadakat Puanınız:',
      'total_points': 'Toplam Puanınız',
      'logout': 'Çıkış Yap',
      'login_benefit': 'Üyelere özel fırsatlardan yararlanmak için giriş yapın.',
      'error': 'Hata',
      'registration_success': 'Kayıt başarılı! Lütfen e-postanızı onaylayın.',
      'invalid_email_format': 'Lütfen geçerli bir e-posta adresi girin.',
      'rate_limit_error': 'Çok fazla deneme. Lütfen birkaç dakika bekleyin.',
      'profile_creation_error': 'Hesap oluşturuldu, ancak profil kurulumu başarısız oldu. Lütfen destekle iletişime geçin.',
      'unknown_error': 'Beklenmedik bir hata oluştu. Lütfen tekrar deneyin.',
      'logout_confirm_title': 'Çıkış Yap',
      'logout_confirm_msg': 'Çıkış yapmak istediğinizden emin misiniz?',
      'yes': 'Evet',
      'no': 'Hayır',
      'account_info': 'Hesap Bilgileri',
      'public_profile': 'Genel Profil',
      'signup_reminder': 'Özel üye avantajları ve sadakat puanları için kayıt olun!',
      'prof_jeweler': 'Kuyumcu',
      'prof_gold_dealer': 'Altın Satıcısı',
      'prof_currency': 'Döviz Bürosu',
      'prof_investor': 'Yatırımcı',
      'prof_other': 'Diğer',
      'select_image': 'Profil Resmi Seç',
      'uploading': 'Yükleniyor...',
      'upload_success': 'Profil resmi güncellendi!',
      'upload_error': 'Yükleme başarısız. Lütfen tekrar deneyin.',
      'cancel': 'İptal',
      'edit': 'Düzenle',
      'code_GA': 'Gram Altın',
      'code_C': 'Çeyrek Altın',
      'code_Y': 'Yarım Altın',
      'code_T': 'Tam Altın',
      'code_CMR': 'Cumhuriyet Altını',
      'code_ATA': 'Ata Altın',
      'code_GAG': 'Gram Gümüş',
      'code_XAUUSD': 'Ons Altın',
      'code_XHGLD': 'Has Altın',
      'code_14': '14 Ayar Altın',
      'code_18': '18 Ayar Altın',
      'code_22': '22 Ayar Bilezik',
      'code_IKB': 'İkibuçuk Altın',
      'code_BSL': 'Beşli Altın',
      'code_GR': 'Gremse Altın',
      'code_RA': 'Reşat Altın',
      'code_HA': 'Hamit Altın',
      'code_XAUXAG': 'Altın/Gümüş Rasyosu',
      'code_USD': 'Dolar',
      'code_EUR': 'Euro',
      'code_AED': 'Dirhem',
      'code_USDT': 'Tether (USDT)',
    },
    'fa': {
      'app_name': '',
      'home': 'خانه',
      'gold': 'طلا',
      'currency': 'ارز',
      'calculate': 'محاسبه',
      'contact': 'تماس',
      'settings': 'تنظیمات',
      'theme': 'تم',
      'language': 'زبان',
      'search_gold': 'جستجوی نوع طلا...',
      'search_currency': 'جستجوی ارز...',
      'last_update': 'آخرین بروزرسانی',
      'offline_data': 'نمایش داده‌های آفلاین',
      'live': 'زنده',
      'offline': 'آفلاین',
      'no_connection': 'بدون اتصال',
      'market_summary': 'خلاصه بازار',
      'my_favorites': 'برگزیده‌های من (۵ تا)',
      'services': 'خدمات ما',
      'contact_channels': 'کانال‌های ارتباطی',
      'telegram_subtitle': 'سیگنال‌ها و اطلاعیه‌های زنده',
      'whatsapp_subtitle': 'خط پشتیبانی سریع',
      'copy_clipboard': 'در حافظه کپی شد!',
      'converter': 'تبدیل‌گر',
      'converter_subtitle': 'مقدار را وارد و دارایی را انتخاب کنید.',
      'amount': 'مقدار',
      'try_amount': 'مقدار لیر',
      'estimated_total': 'مجموع تخمینی (لیر)',
      'purchasable_amount': 'مقدار قابل خرید',
      'quick_calcs': 'محاسبات سریع',
      'gram_gold_10': '۱۰ گرم طلا',
      'dollar_100': '۱۰۰ دلار',
      'quarter_gold_5': '۵ ربع سکه',
      'version': 'نسخه',
      'appearance': 'ظاهر',
      'app_settings': 'تنظیمات برنامه',
      'auto_refresh': 'بروزرسانی خودکار',
      'about': 'درباره',
      'system_default': 'پیش‌فرض سیستم',
      'light': 'روشن',
      'dark': 'تاریک',
      'update_available': 'نسخه جدید موجود است',
      'current_version': 'نسخه فعلی',
      'new_version': 'نسخه جدید',
      'whats_new': 'ویژگی‌های جدید',
      'later': 'بعداً',
      'update': 'بروزرسانی',
      'choose_language': 'انتخاب زبان',
      'choose_language_settings_hint': 'می‌توانید هر زمان که بخواهید این را در تنظیمات تغییر دهید.',
      'continue': 'ادامه',
      'corporate': 'تماس',
      'reliable_market': 'بازارهای معتبر و زنده',
      'gold_bar': 'شمش طلا',
      'gold_swap': 'تبادل ارز',
      'gold_analysis': 'تحلیل طلا',
      'global_rate': 'نرخ جهانی',
      'whatsapp': 'واتس‌اپ',
      'phone_label': 'تلفن',
      'address': 'آدرس',
      'telegram_group': 'گروه تلگرام',
      'choose_theme': 'انتخاب تم',
      'update_interval': 'فواصل بروزرسانی',
      'minutes': 'دقیقه',
      'off': 'خاموش',
      'login': 'ورود',
      'register': 'ثبت نام',
      'profile': 'پروفایل',
      'email': 'ایمیل',
      'password': 'رمز عبور',
      'full_name': 'نام و نام خانوادگی',
      'phone_field': 'شماره تلفن',
      'profession': 'شغل',
      'required': 'الزامی',
      'min_characters': 'حداقل ۶ کاراکتر',
      'loyalty_points': 'امتیاز وفاداری شما:',
      'total_points': 'کل امتیازات',
      'logout': 'خروج',
      'login_benefit': 'برای بهره‌مندی از فرصت‌های ویژه اعضا، وارد شوید.',
      'error': 'خطا',
      'registration_success': 'ثبت نام با موفقیت انجام شد! لطفاً ایمیل خود را تایید کنید.',
      'invalid_email_format': 'لطفا یک آدرس ایمیل معتبر وارد کنید.',
      'rate_limit_error': 'تعداد دفعات تلاش بیش از حد مجاز است. لطفا چند دقیقه صبر کنید.',
      'profile_creation_error': 'حساب کاربری ایجاد شد، اما تنظیم پروفایل با خطا مواجه گردید. لطفا با پشتیبانی تماس بگیرید.',
      'unknown_error': 'خطای غیرمنتظره‌ای رخ داد. لطفا دوباره تلاش کنید.',
      'logout_confirm_title': 'خروج',
      'logout_confirm_msg': 'آیا مطمئن هستید که می‌خواهید خارج شوید؟',
      'yes': 'بله',
      'no': 'خیر',
      'account_info': 'اطلاعات حساب',
      'public_profile': 'پروفایل عمومی',
      'signup_reminder': 'برای مزایای اختصاصی اعضا و امتیاز وفاداری ثبت‌نام کنید!',
      'prof_jeweler': 'جواهرساز',
      'prof_gold_dealer': 'فروشنده طلا',
      'prof_currency': 'صرافی',
      'prof_investor': 'سرمایه‌گذار',
      'prof_other': 'سایر',
      'select_image': 'انتخاب تصویر پروفایل',
      'uploading': 'در حال بارگذاری...',
      'upload_success': 'تصویر پروفایل بروزرسانی شد!',
      'upload_error': 'بارگذاری ناموفق بود. لطفا دوباره تلاش کنید.',
      'cancel': 'لغو',
      'edit': 'ویرایش',
      'code_GA': 'طلای ۱۸ عیار',
      'code_C': 'ربع سکه',
      'code_Y': 'نیم سکه',
      'code_T': 'تمام سکه',
      'code_CMR': 'سکه جمهوریت',
      'code_ATA': 'سکه آتا',
      'code_GAG': 'نقره',
      'code_XAUUSD': 'انس طلا',
      'code_XHGLD': 'طلای خالص',
      'code_14': 'طلای ۱۴ عیار',
      'code_18': 'طلای ۱۸ عیار',
      'code_22': 'دستبند ۲۲ عیار',
      'code_IKB': 'دو و نیم سکه',
      'code_BSL': 'پنج سکه',
      'code_GR': 'سکه گرمسه',
      'code_RA': 'سکه رشاد',
      'code_HA': 'سکه حمید',
      'code_XAUXAG': 'نسبت طلا به نقره',
      'code_USD': 'دلار',
      'code_EUR': 'یورو',
      'code_AED': 'درهم',
      'code_USDT': 'تتر',
    }
  };

  static String translate(BuildContext context, String key) {
    final locale = Localizations.localeOf(context).languageCode;
    final value = _localizedValues[locale]?[key] ?? _localizedValues['tr']?[key] ?? key;
    
    if (key == 'app_name' && value.isEmpty) {
      return UpdateService.localInfo?.appName ?? 'Sarraf Gold';
    }
    
    return value;
  }
}
